### ISSUE TITLE
What's the point of this? :)

### ISSUE THREAD

**Issue by brezal** [dapphub/ds-weth#1]
Hi, there is this erc20 repo already: https://github.com/nexusdev/erc20

What is the point of weth?

**Comment by brezal** [comment]
@dbrock I'm only ignorant and curious, not criticizing you.

**Comment by nmushegian** [comment]
weth replaces [ds-eth-token](https://github.com/nexusdev/ds-eth-token), not erc20. This is a token that wraps native ether into erc20-based ether, not a generic token.

regarding weth vs ds-eth, weth is simpler, it has no dependencies and is a single file with a single contract. This one is basically optimized for being adopted as the official hard-coded contract. This may mean that ds-eth-wrapper gets totally deprecated, we will see
